# See http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  thymeleaf.cache: false
  main.show-banner: false

  # Postgres Configuration
  datasource:
    url: jdbc:postgresql://postgres:5432/meubanco
    username: usuario
    password: senha

  # MongoDB Configuration
  data:
    mongodb:
      uri: mongodb://mongo:27017/meu_mongo_db

  # MySQL Configuration
  mysql:
    datasource:
      url: jdbc:mysql://mysql:3306/meu_mysql_db
      username: root
      password: senha
