# See http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  thymeleaf.cache: false
  main.show-banner: false

  # Postgres Configuration
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  # MongoDB Configuration
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}

  # MySQL Configuration
  mysql:
    datasource:
      url: ${SPRING_DATASOURCE_MYSQL_URL}
      username: ${SPRING_DATASOURCE_MYSQL_USERNAME}
      password: ${SPRING_DATASOURCE_MYSQL_PASSWORD}
